import { db } from '@/lib/firebase';
import { collection, doc, getDocs, setDoc, deleteDoc } from 'firebase/firestore';
import type { DeveloperApiKey } from './types';

/**
 * Loads developer keys generated by the user.
 */
export async function getDeveloperKeys(uid: string): Promise<DeveloperApiKey[]> {
  try {
    const querySnap = await getDocs(collection(db, 'users', uid, 'developer_keys'));
    return querySnap.docs.map(doc => doc.data() as DeveloperApiKey);
  } catch (error) {
    console.error('[Plugin SDK] Error loading developer keys:', error);
    return [];
  }
}

/**
 * Generates a new REST API key.
 */
export async function generateDeveloperKey(uid: string, description: string): Promise<DeveloperApiKey> {
  const keyId = `key_${Math.random().toString(36).substring(7)}`;
  // Mock secure API token format
  const token = `sk_live_${Math.random().toString(36).substring(2)}${Math.random().toString(36).substring(2)}`;

  const key: DeveloperApiKey = {
    id: keyId,
    token,
    description,
    rateLimitLimit: 100, // 100 requests limit
    rateLimitUsed: 0,
    createdAt: new Date().toISOString()
  };

  try {
    await setDoc(doc(db, 'users', uid, 'developer_keys', keyId), key);
  } catch (error) {
    console.error('[Plugin SDK] Error saving developer key:', error);
  }

  return key;
}

/**
 * Revokes/deletes a REST API key.
 */
export async function revokeDeveloperKey(uid: string, keyId: string): Promise<void> {
  try {
    await deleteDoc(doc(db, 'users', uid, 'developer_keys', keyId));
  } catch (error) {
    console.error('[Plugin SDK] Error revoking key:', error);
  }
}
