# Name of the workflow
name: Deploy Frontend to Firebase Hosting

# When this workflow should run
on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          # --- THIS IS THE FIX ---
          # Use Node.js version 20, which is compatible with the latest Firebase tools
          node-version: '20'

      - name: Install and Build
        run: |
          cd frontend
          npm install
          npm run build
        
      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_TOKEN }}'
          channelId: live
          projectId: '${{ secrets.FIREBASE_PROJECT_ID }}'
          entryPoint: ./frontend

